theme: jekyll-theme-cayman

title: LiSA
description: A Library for Static Analysis
google_analytics: G-S6MJSTDQJL

exclude:
  [
    README.md,
    release.sh,
    check-links.sh,
    subtypes-scanner,
    subtypes.yaml,
    vendor,
    schemes/*.tex,
    schemes/generator.py,
  ]

ssv-homepage: https://unive-ssv.github.io/
