theme: jekyll-theme-cayman

title: LiSA
description: A Library for Static Analysis
google_analytics: G-S6MJSTDQJL

exclude:
  [
    README.md,
    release.sh,
    check-links.sh,
    schemes.tex,
    schemes.pdf,
    schemes.aux,
    schemes.fdb_latexmk,
    schemes.log,
    schemes.out,
    schemes.synctex.gz,
    schemes.xdv,
    schemes.fls,
    subtypes-scanner,
    subtypes.yaml,
  ]

ssv-homepage: https://unive-ssv.github.io/
