name: Build and deploy site

on:
  push:
    branches: ["master"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
      - name: Install dependencies
        run: bundle install
      - name: "Set up JDK 11"
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Generate alternatives for configuration page
        run: |
          cd subtypes-scanner
          chmod +x gradlew
          # TODO should add some parameter for this
          ./graldew run --args="0.2"
          cd ..
      - name: Check for broken links
        run: |
          gem install html-proofer
          bundle exec jekyll build
          # TODO restore check for internal hashes once website is complete
          # in local checks, add --ignore-urls "/localhost:4000/"
          htmlproofer ./_site --check-internal-hash false --ignore-status-codes "403,521"
      - name: Build site
        run: bundle exec jekyll build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Pages
        uses: actions/deploy-pages@v4
